services:
  app:
    image: python:3.10-alpine
    container_name: backend-container
    working_dir: /backend/app/src
    # Monta el directorio ../backend local en el directorio /backend del contenedor
    # de forma que los cambios en un directorio se reflejan en el otro y viceversa
    volumes:
      - .:/backend
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
    ports:
      - "5000:5000"
    command: sh -c "apk add --no-cache python3-dev sqlite nano && pip3 install --upgrade pip && pip3 --no-cache-dir install -r /backend/app/src/requirements.txt && gunicorn -k gthread -w 1 --threads 6 --timeout 0 -b 0.0.0.0:5000 app:app --log-level=debug"