services:
  app:
    image: python:3.9-alpine
    container_name: backend-container
    working_dir: /backend
    # Monta el directorio ../backend local en el directorio /backend del contenedor
    # de forma que los cambios en un directorio se reflejan en el otro y viceversa
    volumes:
      - .:/backend
    environment:
      - PYTHONUNBUFFERED=1
    command: sh -c "apk add --no-cache python3-dev sqlite nano && pip3 install --upgrade pip && pip3 --no-cache-dir install -r requirements.txt && tail -f /dev/null"
