openapi: 3.0.0
info:
  title: API de Noizz
  version: 1.0.0
  description: API de la aplicacion de reproduccion de musica Noizz

servers:
  - url: http://api-noizz.onrender.com
    description: Servidor local

paths:
  /login:
    $ref: "/static/docs/paths/auth/login.yaml"
  /logout:
    $ref: "/static/docs/paths/auth/logout.yaml"
  /register-oyente:
    $ref: "/static/docs/paths/auth/register-oyente.yaml"
  /register-artista:
    $ref: "/static/docs/paths/auth/register-artista.yaml"
  /get-pendientes:
    $ref: "/static/docs/paths/admin/get-pendientes.yaml"
  /check-artista:
    $ref: "/static/docs/paths/admin/check-artista.yaml"
  /verify-artista:
    $ref: "/static/docs/paths/auth/verify-artista.yaml"
  /change-datos-artista:
    $ref: "/static/docs/paths/artista/change-datos-artista.yaml"
  /change-biografia:
    $ref: "/static/docs/paths/artista/change-biografia.yaml"
  /get-datos-artista:
    $ref: "/static/docs/paths/artista/get-datos-artista.yaml"
  /delete-account:
    $ref: "/static/docs/paths/auth/delete-account.yaml"
  /forgot-password:
    $ref: "/static/docs/paths/auth/forgot-password.yaml"
  /verify-codigo:
    $ref: "/static/docs/paths/auth/verify-codigo.yaml"
  /reset-password:
    $ref: "/static/docs/paths/auth/reset-password.yaml"
  /get-datos-album:
    $ref: "/static/docs/paths/album/get-datos-album.yaml"
  /delete-album:
    $ref: "/static/docs/paths/album/delete-album.yaml"
  /change-album:
    $ref: "/static/docs/paths/album/change-album.yaml"
  /create-album:
    $ref: "/static/docs/paths/album/create-album.yaml"
  /change-contrasenya:
    $ref: "/static/docs/paths/oyente/change-contrasenya.yaml"
  /get-datos-oyente:
    $ref: "/static/docs/paths/oyente/get-datos-oyente.yaml"
  /get-historial-artistas:
    $ref: "/static/docs/paths/oyente/get-historial-artistas.yaml"
  /change-datos-oyente:
    $ref: "/static/docs/paths/oyente/change-datos-oyente.yaml"
  /get-historial-canciones:
    $ref: "/static/docs/paths/oyente/get-historial-canciones.yaml"
  /get-historial-colecciones:
    $ref: "/static/docs/paths/oyente/get-historial-colecciones.yaml"
  /get-mis-playlists:
    $ref: "/static/docs/paths/oyente/get-mis-playlists.yaml"
  /get-recomendaciones:
    $ref: "/static/docs/paths/oyente/get-recomendaciones.yaml"
  /get-seguidos:
    $ref: "/static/docs/paths/oyente/get-seguidos.yaml"
  /add-reproduccion:
    $ref: "/static/docs/paths/song/add-reproduccion.yaml"
  /create-cancion:
    $ref: "/static/docs/paths/song/create-cancion.yaml"
  /change-fav:
    $ref: "/static/docs/paths/song/change-fav.yaml"
  /change-progreso:
    $ref: "/static/docs/paths/song/change-progreso.yaml"
  /delete-cancion:
    $ref: "/static/docs/paths/song/delete-cancion.yaml"
  /get-cancion-actual:
    $ref: "/static/docs/paths/song/get-cancion-actual.yaml"
  /play-pause:
    $ref: "/static/docs/paths/song/play-pause.yaml"
  /put-cancion-sola:
    $ref: "/static/docs/paths/song/put-cancion-sola.yaml"
  /put-cancion-coleccion:
    $ref: "/static/docs/paths/song/put-cancion-coleccion.yaml"
  /accept-invitacion:
    $ref: "/static/docs/paths/playlist/accept-invitacion.yaml"
  /add-to-playlist:
    $ref: "/static/docs/paths/playlist/add-to-playlist.yaml"
  /change-playlist:
    $ref: "/static/docs/paths/playlist/change-playlist.yaml"
  /change-privacidad:
    $ref: "/static/docs/paths/playlist/change-privacidad.yaml"
  /create-playlist:
    $ref: "/static/docs/paths/playlist/create-playlist.yaml"
  /delete-from-playlist:
    $ref: "/static/docs/paths/playlist/delete-from-playlist.yaml"
  /delete-invitacion:
    $ref: "/static/docs/paths/playlist/delete-invitacion.yaml"
  /delete-playlist:
    $ref: "/static/docs/paths/playlist/delete-playlist.yaml"
  /expel-from-playlist:
    $ref: "/static/docs/paths/playlist/expel-from-playlist.yaml"
  /get-datos-playlist:
    $ref: "/static/docs/paths/playlist/get-datos-playlist.yaml"
  /invite-to-playlist:
    $ref: "/static/docs/paths/playlist/invite-to-playlist.yaml"
  /leave-playlist:
    $ref: "/static/docs/paths/playlist/leave-playlist.yaml"

components:
  securitySchemes:
    bearerAuth:
      $ref: "/static/docs/components/token.yaml#/components/securitySchemes/bearerAuth"
