openapi: 3.0.0
info:
  title: API de Noizz
  version: 1.0.0
  description: API de la aplicacion de reproduccion de musica Noizz

servers:
  - url: http://api-noizz.onrender.com
    description: Servidor local

paths:
  /login:
    $ref: "/static/docs/paths/auth/login.yaml"
  /logout:
    $ref: "/static/docs/paths/auth/logout.yaml"
  /register-oyente:
    $ref: "/static/docs/paths/auth/register-oyente.yaml"
  /register-artista:
    $ref: "/static/docs/paths/auth/register-artista.yaml"
  /get-pendientes:
    $ref: "/static/docs/paths/admin/get-pendientes.yaml"
  /check-artista:
    $ref: "/static/docs/paths/admin/check-artista.yaml"
  /verify-artista:
    $ref: "/static/docs/paths/auth/verify-artista.yaml"
  /delete-account:
    $ref: "/static/docs/paths/auth/delete-account.yaml"
  /forgot-password:
    $ref: "/static/docs/paths/auth/forgot-password.yaml"
  /verify-codigo:
    $ref: "/static/docs/paths/auth/verify-codigo.yaml"
  /reset-password:
    $ref: "/static/docs/paths/auth/reset-password.yaml"
  /get-historial-artistas:
    $ref: "/static/docs/paths/home/get-historial-artistas.yaml"
  /get-historial-canciones:
    $ref: "/static/docs/paths/home/get-historial-canciones.yaml"
  /get-historial-colecciones:
    $ref: "/static/docs/paths/home/get-historial-colecciones.yaml"
  /get-mis-playlists:
    $ref: "/static/docs/paths/home/get-mis-playlists.yaml"
  /get-recomendaciones:
    $ref: "/static/docs/paths/home/get-recomendaciones.yaml"
  /get-seguidos:
    $ref: "/static/docs/paths/home/get-seguidos.yaml"
  /add-reproduccion:
    $ref: "/static/docs/paths/song/add-reproduccion.yaml"
  /change-fav:
    $ref: "/static/docs/paths/song/change-fav.yaml"
  /change-progreso:
    $ref: "/static/docs/paths/song/change-progreso.yaml"
  /get-cancion-actual:
    $ref: "/static/docs/paths/song/get-cancion-actual.yaml"
  /play-pause:
    $ref: "/static/docs/paths/song/play-pause.yaml"
  /put-cancion-sola:
    $ref: "/static/docs/paths/song/put-cancion-sola.yaml"
  /put-cancion-coleccion:
    $ref: "/static/docs/paths/song/put-cancion-coleccion.yaml"

components:
  securitySchemes:
    bearerAuth:
      $ref: "/static/docs/components/token.yaml#/components/securitySchemes/bearerAuth"
